"""Initial migration.

Revision ID: 531f2394609a
Revises: 
Create Date: 2025-04-03 02:28:04.438626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531f2394609a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###
